# Análisis de los baremos del NASA-TX

Este fichero permite la lectura de los ficheros de NASA-TX finales y el fichero de peso. 




In [15]:
import pandas as pd
import os
import numpy as np



def leer_csv_pandas(directorio, nombre_archivo):
    """
    Lee un fichero CSV usando la biblioteca 'pandas'.

    Args:
        directorio (str): La ruta al directorio donde se encuentra el archivo.
        nombre_archivo (str): El nombre completo del archivo CSV (ej: 'datos.csv').
    """
    ruta_completa = os.path.join(directorio, nombre_archivo)

    try:
        # La función read_csv es muy flexible y potente
        df = pd.read_csv(ruta_completa)

        #print(f"**Contenido de '{nombre_archivo}' (usando 'pandas'):**")
        # Imprime el DataFrame (tabla de datos)
        #print(df)
        #df.head()
        #print("\n--- Información del DataFrame ---")
        # Muestra un resumen de las columnas, tipos de datos, etc.
        df.info()
       # print("---------------------------------------")
        return df

    except FileNotFoundError:
        print(f"❌ Error: El archivo '{ruta_completa}' no se encontró.")
    except Exception as e:
        print(f"❌ Ocurrió un error al leer el archivo: {e}")

# --- Ejemplo de uso ---
# **¡IMPORTANTE!** Cambia estas rutas y nombre de archivo por los reales.
DIRECTORIO_CSV = './' 
NOMBRE_FICHERO = 'NASA_weights.csv'

weights=leer_csv_pandas(DIRECTORIO_CSV,NOMBRE_FICHERO)
weights.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sujeto       4 non-null      object 
 1   Mental       4 non-null      float64
 2   Física       4 non-null      float64
 3   Temporal     4 non-null      float64
 4   Rendimiento  4 non-null      float64
 5   Esfuerzo     4 non-null      float64
 6   Frustración  4 non-null      float64
 7   Tipo         2 non-null      object 
dtypes: float64(6), object(2)
memory usage: 384.0+ bytes


Sujeto  Mental  Física  Temporal  Rendimiento  Esfuerzo  Frustración  \
0  Prueba1     4.0     3.0       2.0          3.0       2.0          1.0   
1       P3     3.0     4.0       1.0          3.0       1.0          3.0   
2       P2     4.0     3.0       2.0          2.0       2.0          2.0   
3       P4     5.0     4.0       3.0          2.0       1.0          0.0   

                   Tipo  
0                   NaN  
1                   NaN  
2  Joystick inalámbrico  
3  Joystick inalámbrico

In [16]:


NOMBRE_FICHERO = 'SAMU_ Test NASA-TX_1.csv'

data =leer_csv_pandas(DIRECTORIO_CSV, NOMBRE_FICHERO)
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column                                                                                                                            Non-Null Count  Dtype 
---  ------                                                                                                                            --------------  ----- 
 0   Timestamp                                                                                                                         4 non-null      object
 1   Identificación
(Acrónimo asignado)                                                                                                4 non-null      object
 2   Tipo de experimento
                                                                                                              4 non-null      object
 3   Exigencia Mental
 ¿Cuánta actividad mental y perceptiva fue necesaria? (Pensar, decidir, recordar, buscar

Timestamp Identificación\n(Acrónimo asignado)  \
0  11/10/2025 12:31:34                                  P2   
1  11/10/2025 12:31:55                                  P2   
2  11/10/2025 12:32:16                                  P3   
3  11/10/2025 15:24:14                                  P4   

          Tipo de experimento\n  \
0          Joystick inalámbrico   
1  Manual asistido por el motor   
2          Joystick inalámbrico   
3          Joystick inalámbrico   

   Exigencia Mental\n ¿Cuánta actividad mental y perceptiva fue necesaria? (Pensar, decidir, recordar, buscar).  \
0                                                 10                                                              
1                                                  5                                                              
2                                                  9                                                              
3                                                 10                                                              

   Exigencia Física\n ¿Cuánta actividad física fue necesaria? (Empujar, tirar, accionar).  \
0                                                  5                                        
1                                                  5                                        
2                                                  9                                        
3                                                 10                                        

   Exigencia Temporal (T)\n¿Cuánta presión de tiempo sintió debido al ritmo de las tareas? (Ritmo lento/rápido).  \
0                                                 10                                                               
1                                                  5                                                               
2                                                  9                                                               
3                                                 10                                                               

   Rendimiento (R)\n¿Hasta qué punto cree que tuvo éxito en alcanzar los objetivos? (Buena/Mala performance).  \
0                                                  5                                                            
1                                                  5                                                            
2                                                  9                                                            
3                                                  0                                                            

   Esfuerzo (E)\n¿En qué medida tuvo que trabajar (física o mentalmente) para alcanzar su nivel de resultados?  \
0                                                  0                                                             
1                                                  5                                                             
2                                                  9                                                             
3                                                 10                                                             

   Nivel de Frustración (Fr)\n¿En qué medida se sintió inseguro, irritado, tenso, o por el contrario, seguro, contento y satisfecho?  
0                                                 10                                                                                  
1                                                 10                                                                                  
2                                                  9                                                                                  
3                                                 10

Hay que multiplicar por 2 el resultado
Invertir Rendimiento
Escalar por los pesos


In [21]:

nombre_columnas = ['Sujeto','Tipo','NASA']
resultado = pd.DataFrame(np.zeros((data.shape[0],3)),columns=nombre_columnas)

for s in np.arange(data.shape[0]):
    fila_sel = (weights['Sujeto'] == data.iloc[s,1]) & (weights['Tipo'] == data.iloc[s,2])
    pesos= weights[fila_sel]
    if len(pesos)!=0:
        print(pesos)
        resultado.iloc[s,0]=data.iloc[s,1]
        resultado.iloc[s,1]=data.iloc[s,2]
        data.iloc[s,6]=10-data.iloc[s,6]
        producto = 10*np.array(pesos.iloc[0,1:7])*np.array(data.iloc[s,3:9])
        print(np.array(data.iloc[s,3:9]))
        print(producto)
        resultado.iloc[s,2]= producto.sum()/15
    
resultado.head()

  Sujeto  Mental  Física  Temporal  Rendimiento  Esfuerzo  Frustración  \
2     P2     4.0     3.0       2.0          2.0       2.0          2.0   

                   Tipo  
2  Joystick inalámbrico  
[10 5 10 5 0 10]
[400.0 150.0 200.0 100.0 0.0 200.0]
  Sujeto  Mental  Física  Temporal  Rendimiento  Esfuerzo  Frustración  \
3     P4     5.0     4.0       3.0          2.0       1.0          0.0   

                   Tipo  
3  Joystick inalámbrico  
[10 10 10 10 10 10]
[500.0 400.0 300.0 200.0 100.0 0.0]


Sujeto                  Tipo   NASA
0     P2  Joystick inalámbrico   70.0
1    0.0                   0.0    0.0
2    0.0                   0.0    0.0
3     P4  Joystick inalámbrico  100.0

# 🚀 Interpretación del NASA-TLX (NASA-Task Load Index)

El NASA-TLX es una herramienta **comparativa** para evaluar la **carga mental subjetiva** de una tarea, con una
puntuación final en una escala de **0 a 100**.

---

## 🔢 Interpretación del Índice Global (Puntuación Final)

La puntuación global indica el nivel general de demanda de la tarea.

| Rango de Puntuación (0-100) | Interpretación General |
| :--- | :--- |
| **0 - ~20** | **Carga Muy Baja:** Tarea muy fácil y con poco esfuerzo. |
| **~40 - ~60** | **Carga Media/Moderada:** Demanda notable, pero sostenible. |
| **~80 - 100** | **Carga Muy Alta/Excesiva:** Tarea llevada al límite, alto riesgo de fatiga y error. |

> **Uso Principal:** El valor es más útil cuando se **compara** una condición (ej. interfaz A) con otra (ej. interfaz B) para determinar cuál es menos demandante.

---

## 📊 Interpretación de las 6 Dimensiones Individuales

Observar las puntuaciones altas en las subescalas permite identificar **la naturaleza** de la carga (dónde se concentra la demanda).

| Dimensión | Significado de Puntuación Alta | Implicación |
| :--- | :--- | :--- |
| **Exigencia Mental** | Alta necesidad de pensar, decidir o recordar. | Complejidad cognitiva o de la información. |
| **Exigencia Temporal** | Gran presión de tiempo o ritmo de trabajo rápido. | Problemas de plazos o cadencia de la tarea. |
| **Esfuerzo** | Alto grado de recursos invertidos para mantener el rendimiento. | El sujeto tuvo que **esforzarse mucho** para tener éxito. |
| **Frustración** | Alto nivel de sentirse irritado, estresado o descontento. | Diseño deficiente o interrupciones. |
| **Exigencia Física** | Alto requerimiento de esfuerzo muscular o movimiento. | Problemas ergonómicos. |
| **Rendimiento** (Invertida) | El sujeto siente que su **rendimiento fue deficiente** (Puntuación bruta original fue baja). | Fracaso en el logro de objetivos, baja sensación de eficacia. |

### 🚨 Recordatorio Clave: Inversión del Rendimiento

Para el cálculo final ponderado, la puntuación de **Rendimiento (Performance)** se debe **invertir** para que una puntuación baja en la subescala contribuya a una carga mental alta en el resultado final:

$$R'_{\text{OP}} = 100 - R_{\text{OP}}$$

210.0
