# Análisis de confort en la navegación

Comfort during navigation: According to [15], comfort or discomfort in navigation is related to
variations in the wheelchair’s acceleration. This is determined by averaging the second derivative
of the wheelchair’s velocity in each section.

[15] Fr´ed´eric Leishman, Vincent Monfort, Odile Horn, and Guy Bourhis. Driving assistance by deictic
control for a smart wheelchair: The assessment issue. IEEE Transactions on Human-Machine
Systems, 44(1):66–77, 2013.

PARECE QUE ESE ARTÍCULO NO ES (VERIFICAR)

Lo que busca este programa es, a partir de la lectura de los Hall, que se reciben cada intervalo de tiempo específico, se determina la velocidad de cada rueda, la velocidad lineal y angular, y se estiman sus segundas derivadas mediante filtro de Savitzky-Golay para reducir el ruido. 

In [7]:
import numpy as np
from scipy.signal import savgol_filter


def calcular_aceleracion_y_jerk(velocidad, dt, window_length=7, polyorder=3):
    """
    Calcula la aceleración y su derivada (jerk) a partir de una serie temporal de 
    distancias recorridas entre muestras consecutivas, usando el filtro de Savitzky-Golay.

    Parámetros:
    -----------
    distancias : array-like
        Lista o array con las distancias recorridas entre cada muestra.
    dt : float
        Intervalo de muestreo en segundos.
    window_length : int, opcional
        Tamaño de la ventana para Savitzky-Golay (debe ser impar y > polyorder).
    polyorder : int, opcional
        Orden del polinomio usado en Savitzky-Golay.

    Retorna:
    --------
    aceleracion : np.ndarray
        Array con los valores de aceleración estimados (m/s^2).
    jerk : np.ndarray
        Array con los valores de la derivada de la aceleración (m/s^3).
    """
#    distancias = np.array(distancias)

    # Aceleración (1ª derivada de velocidad)
    #aceleracion = savgol_filter(velocidad, window_length, polyorder, deriv=1, delta=dt)

    # Jerk (derivada de la aceleración, es decir 2ª derivada de la velocidad)
    jerk = savgol_filter(velocidad, window_length, polyorder, deriv=2, delta=dt)

    #return aceleracion, jerk
    return jerk

def  calcula_jerk(data,dt=1):
    vl = (data[0,:]+data[1,:])/(2*dt)
    vg = (data[0,:]-data[1,:])/dt
    print(vl)
    print(vg)
    
    jerkl = calcular_aceleracion_y_jerk(vl,dt)
    jerkg = calcular_aceleracion_y_jerk(vg,dt)
    return jerkl,jerkg
# Intervalo de muestreo
dt = 1
data = np.array([[1,2,3,2,1,2,3,3,3,3],[5,1,2,2,1,2,3,3,3,3]])

print(calcula_jerk(data))

[3.  1.5 2.5 2.  1.  2.  3.  3.  3.  3. ]
[-4.  1.  1.  0.  0.  0.  0.  0.  0.  0.]
(array([-0.22619048, -0.05952381,  0.10714286,  0.27380952,  0.1547619 ,
        0.17857143, -0.04761905, -0.38095238, -0.71428571, -1.04761905]), array([-3.54761905, -2.54761905, -1.54761905, -0.54761905,  0.11904762,
        0.11904762,  0.        ,  0.        ,  0.        ,  0.        ]))


In [2]:
print((data[0,:]+data[1,:])/2)

[3.  1.5 2.5 2.  1.  2.  3.  3.  3.  1.5]
